### ISSUE TITLE
0.12 buffer inconsistencies

### ISSUE THREAD

**Issue by harking** [dconstructing/rfm69#7]
After upgrading to 0.12 if started noticing that the receive buffer had corrupted data about 50% of receives. 

Have you seen this too? Is there a fix? Where should I look to fix it myself?  

Thanks!

**Comment by losttime** [comment]
Are you referring to node version 0.12? I've only used node 0.10.28 (because that's all I could get installed on my Pi after various attempts).

I have been noticing some issues, but I don't think it's specifically related to data read from the buffer, and it's been nowhere near 50% of messages (maybe more like 5%).

Are you sure the module sending the message has the same encryption key as the module receiving the message? That's a potential source of failure.

This library uses [`pi-spi`](https://github.com/natevw/pi-spi) to actually communicate with the RFM69 module. There may be an issue with `pi-spi`, or the underlying spi mechanisms in the OS.

**Comment by harking** [comment]
Turns out it was just the connections that the radio had on the transmitting side. Everything is working well so far with 0.12 after I corrected the TX

**Comment by losttime** [comment]
Quite a relief :)
